snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
        event_publisher:
            type: predis
            alias: event_publisher
            dsn: "%env(REDIS_URL)%"
