apiVersion: v1
kind: Service
metadata:
  name: web3pulse-app-service
  namespace: web3pulse
spec:
  selector:
    app: web3pulse-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
